export const DOCTORS_FETCH_SUCCESS = "DOCTORS_FETCH_SUCCESS";
export const DOCTOR_FETCH_SUCCESS = 'DOCTOR_FETCH_SUCCESS';
export const PATIENTS_FETCH_SUCCESS = 'PATIENTS_FETCH_SUCCESS';
export const PATIENT_FETCH_SUCCESS = 'PATIENT_FETCH_SUCCESS';
export const APPOINTMENT_INTERVALS_FETCH_SUCCESS = 'APPOINTMENT_INTERVALS_FETCH_SUCCESS';
export const APPOINTMENTS_FETCH_SUCCESS = 'APPOINTMENTS_FETCH_SUCCESS'